### ISSUE TITLE
更新チェック中にスレッドをクリックしても反応しない

### ISSUE THREAD

**Issue by EarlgreyPicard** [gomita/foxage5ch#2]
更新チェック実行中にスレッドを開こうとクリックしても受け付けてくれない場合がありました。
- - -
あらためて確認したところスレッドを開いてくれました。他の原因があったのかもしれません。

**Comment by gomita** [comment]
1個の板の更新チェックが完了するたびにツリー全体が再描画されていたためでした。
修正しました。commit:8984aaedda12e89beacb54902ff4e5ab59571e1c

**Comment by gomita** [comment]
Ver.5.0.2にて、通常ツリー表示の場合、更新チェック後にスレが再描画されない副作用があったため、再度修正。
commit cb951c63499aec110602f1fd4f3f87b6bd19ed9e
