### ISSUE TITLE
スレッドタイトルの©が入っていた場合に &H169; のまま出している

### ISSUE THREAD

**Issue by EarlgreyPicard** [gomita/foxage5ch#3]
スレッドタイトルでよく使用される特殊文字の数値文字参照の変換に対応していただければと思います。

**Comment by gomita** [comment]
修正しました。次回タイトル取得時以降、&#169;が©で表示されます。
また、「©2ch.net」はもともとタイトル取得時にカットする仕様だったところ動作しなくなっていたので、こちらも併せて修正済みです。
